/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["appGetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service version */
        get: operations["appGetVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create and publish a profile
         * @description Compound operation that creates a profile memory, publishes it to the
         *     'profiles' space — all in one call.
         *     Equivalent to: createMemory → publishToSpace (2 svc calls collapsed to 1).
         */
        post: operations["appCreateAndPublishProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/profiles/{memoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Retract a profile
         * @description Compound operation that retracts the profile from the profiles space
         *     The underlying memory is soft-deleted.
         */
        delete: operations["appRetractProfile"];
        options?: never;
        head?: never;
        /**
         * Update and republish a profile
         * @description Compound operation that updates the profile memory content, then
         *     republishes to the profiles space.
         */
        patch: operations["appUpdateAndRepublishProfile"];
        trace?: never;
    };
    "/api/app/v1/profiles/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search published profiles
         * @description Searches the profiles space for published user profiles.
         *     Returns enriched results with user_id, display_name, etc.
         */
        post: operations["appSearchProfiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a memory */
        post: operations["appCreateMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/memories/{memoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft delete a memory */
        delete: operations["appDeleteMemory"];
        options?: never;
        head?: never;
        /** Update a memory */
        patch: operations["appUpdateMemory"];
        trace?: never;
    };
    "/api/app/v1/memories/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hybrid search (BM25 + semantic) */
        post: operations["appSearchMemories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/memories/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find similar memories by vector similarity */
        post: operations["appFindSimilarMemories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/memories/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Semantic query (vector-only) */
        post: operations["appQueryMemories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a relationship between memories */
        post: operations["appCreateRelationship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/relationships/{relationshipId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a relationship */
        delete: operations["appDeleteRelationship"];
        options?: never;
        head?: never;
        /** Update a relationship */
        patch: operations["appUpdateRelationship"];
        trace?: never;
    };
    "/api/app/v1/relationships/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search relationships */
        post: operations["appSearchRelationships"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/spaces/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a memory to shared spaces
         * @description Publishes a memory to the specified shared spaces.
         *     Returns a confirmation token that must be confirmed via the svc confirmations endpoint.
         */
        post: operations["appPublishToSpace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/spaces/retract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retract a memory from shared spaces
         * @description Retracts a memory from shared spaces.
         *     Returns a confirmation token that must be confirmed via the svc confirmations endpoint.
         */
        post: operations["appRetractFromSpace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/spaces/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revise content in a space
         * @description Revises content in a shared space.
         *     Returns a confirmation token that must be confirmed via the svc confirmations endpoint.
         */
        post: operations["appReviseInSpace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/spaces/moderate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Moderate content in a space or group */
        post: operations["appModerateSpace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/spaces/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search shared spaces */
        post: operations["appSearchSpaces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/spaces/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Semantic query across shared spaces */
        post: operations["appQuerySpaces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/trust/ghost-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ghost configuration */
        get: operations["appGetGhostConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update ghost configuration */
        patch: operations["appUpdateGhostConfig"];
        trace?: never;
    };
    "/api/app/v1/trust/set-user-trust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set trust level for a specific user */
        post: operations["appSetUserTrust"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/trust/remove-user-trust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove custom trust level (revert to default) */
        post: operations["appRemoveUserTrust"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/trust/block-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block a user */
        post: operations["appBlockUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/trust/unblock-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unblock a user */
        post: operations["appUnblockUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/trust/check-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check memory access for a user */
        post: operations["appCheckAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/trust/search-as-ghost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search memories as ghost (compound operation)
         * @description Compound operation unique to the web tier. Resolves the caller's trust level
         *     for the target user, builds a ghost_context, and executes a trust-filtered
         *     search — all in one call. The svc tier requires the caller to resolve
         *     ghost_context themselves and pass it to the search endpoint.
         */
        post: operations["appSearchAsGhost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/v1/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user preferences */
        get: operations["appGetPreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user preferences */
        patch: operations["appUpdatePreferences"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /** @enum {string} */
                kind: "validation" | "not_found" | "unauthorized" | "forbidden" | "conflict" | "rate_limit" | "external" | "internal";
                message: string;
                context: {
                    [key: string]: unknown;
                };
            };
        };
        /** @enum {string} */
        ContentType: "code" | "note" | "documentation" | "reference" | "todo" | "checklist" | "project" | "goal" | "habit" | "email" | "conversation" | "meeting" | "person" | "article" | "webpage" | "social" | "image" | "video" | "audio" | "song" | "transcript" | "presentation" | "spreadsheet" | "pdf" | "screenplay" | "recipe" | "idea" | "quote" | "poetry" | "journal" | "memory" | "event" | "bookmark" | "form" | "location" | "invoice" | "contract" | "system" | "action" | "audit" | "history" | "ghost" | "comment";
        /**
         * @default exclude
         * @enum {string}
         */
        DeletedFilter: "exclude" | "include" | "only";
        SearchFilters: {
            types?: components["schemas"]["ContentType"][];
            tags?: string[];
            weight_min?: number;
            weight_max?: number;
            trust_min?: number;
            trust_max?: number;
            /** Format: date-time */
            date_from?: string;
            /** Format: date-time */
            date_to?: string;
            has_relationships?: boolean;
        };
        /** @enum {string} */
        ModerationAction: "approve" | "reject" | "remove";
        /**
         * @default approved
         * @enum {string}
         */
        ModerationFilter: "approved" | "pending" | "rejected" | "removed" | "all";
        CreateProfileInput: {
            display_name: string;
            bio?: string;
            tags?: string[];
        };
        UpdateProfileInput: {
            display_name?: string;
            bio?: string;
            tags?: string[];
        };
        SearchProfilesInput: {
            query: string;
            /** @default 10 */
            limit: number;
            /** @default 0 */
            offset: number;
        };
        CreateProfileResult: {
            memory_id: string;
            space_id: string;
            composite_id: string;
        };
        UpdateProfileResult: {
            memory_id: string;
            composite_id: string;
        };
        SearchProfilesResult: {
            profiles: components["schemas"]["ProfileSearchResult"][];
            total: number;
            offset: number;
            limit: number;
            hasMore: boolean;
        };
        ProfileSearchResult: {
            user_id: string;
            display_name: string;
            bio?: string;
            tags: string[];
            similarity: number;
            memory_id: string;
            composite_id: string;
        };
        CreateMemoryInput: {
            content: string;
            title?: string;
            type?: components["schemas"]["ContentType"];
            weight?: number;
            trust?: number;
            tags?: string[];
            references?: string[];
            parent_id?: string | null;
            thread_root_id?: string | null;
            context_summary?: string;
            context_conversation_id?: string;
        };
        SearchMemoryInput: {
            query: string;
            /** @default 0.7 */
            alpha: number;
            /** @default 10 */
            limit: number;
            /** @default 0 */
            offset: number;
            filters?: components["schemas"]["SearchFilters"];
            /** @default true */
            include_relationships: boolean;
            deleted_filter?: components["schemas"]["DeletedFilter"];
        };
        FindSimilarInput: {
            memory_id?: string;
            text?: string;
            /** @default 10 */
            limit: number;
            /** @default 0.7 */
            min_similarity: number;
            deleted_filter?: components["schemas"]["DeletedFilter"];
        };
        QueryMemoryInput: {
            query: string;
            /** @default 5 */
            limit: number;
            /** @default 0.6 */
            min_relevance: number;
            filters?: components["schemas"]["SearchFilters"];
            deleted_filter?: components["schemas"]["DeletedFilter"];
        };
        UpdateMemoryInput: {
            content?: string;
            title?: string;
            type?: string;
            weight?: number;
            trust?: number;
            tags?: string[];
            references?: string[];
            parent_id?: string | null;
            thread_root_id?: string | null;
        };
        DeleteMemoryInput: {
            reason?: string;
        };
        CreateMemoryResult: {
            memory_id: string;
            /** Format: date-time */
            created_at: string;
        };
        SearchMemoryResult: {
            memories: {
                [key: string]: unknown;
            }[];
            relationships?: {
                [key: string]: unknown;
            }[];
            total: number;
            offset: number;
            limit: number;
            hasMore: boolean;
        };
        FindSimilarResult: {
            similar_memories: ({
                id: string;
                similarity: number;
            } & {
                [key: string]: unknown;
            })[];
            total: number;
        };
        QueryMemoryResult: {
            memories: ({
                id: string;
                relevance: number;
            } & {
                [key: string]: unknown;
            })[];
            total: number;
        };
        UpdateMemoryResult: {
            memory_id: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
            updated_fields: string[];
        };
        DeleteMemoryResult: {
            memory_id: string;
            /** Format: date-time */
            deleted_at: string;
            orphaned_relationship_ids: string[];
        };
        CreateRelationshipInput: {
            memory_ids: string[];
            relationship_type: string;
            observation: string;
            /** @default 0.5 */
            strength: number;
            /** @default 0.8 */
            confidence: number;
            tags?: string[];
            context_summary?: string;
            context_conversation_id?: string;
        };
        SearchRelationshipInput: {
            query: string;
            relationship_types?: string[];
            strength_min?: number;
            confidence_min?: number;
            tags?: string[];
            /** @default 10 */
            limit: number;
            /** @default 0 */
            offset: number;
            deleted_filter?: components["schemas"]["DeletedFilter"];
        };
        UpdateRelationshipInput: {
            relationship_type?: string;
            observation?: string;
            strength?: number;
            confidence?: number;
            tags?: string[];
        };
        CreateRelationshipResult: {
            relationship_id: string;
            memory_ids: string[];
            /** Format: date-time */
            created_at: string;
        };
        SearchRelationshipResult: {
            relationships: {
                [key: string]: unknown;
            }[];
            total: number;
            offset: number;
            limit: number;
            hasMore: boolean;
        };
        UpdateRelationshipResult: {
            relationship_id: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
            updated_fields: string[];
        };
        DeleteRelationshipResult: {
            relationship_id: string;
            memories_updated: number;
        };
        PublishInput: {
            memory_id: string;
            spaces?: string[];
            groups?: string[];
            additional_tags?: string[];
        };
        RetractInput: {
            memory_id: string;
            spaces?: string[];
            groups?: string[];
        };
        ReviseInput: {
            memory_id: string;
        };
        ModerateInput: {
            memory_id: string;
            space_id?: string;
            group_id?: string;
            action: components["schemas"]["ModerationAction"];
            reason?: string;
        };
        SearchSpaceInput: {
            query: string;
            spaces?: string[];
            groups?: string[];
            /**
             * @default hybrid
             * @enum {string}
             */
            search_type: "hybrid" | "bm25" | "semantic";
            content_type?: string;
            tags?: string[];
            min_weight?: number;
            max_weight?: number;
            /** Format: date-time */
            date_from?: string;
            /** Format: date-time */
            date_to?: string;
            moderation_filter?: components["schemas"]["ModerationFilter"];
            include_comments?: boolean;
            /** @default 10 */
            limit: number;
            /** @default 0 */
            offset: number;
        };
        QuerySpaceInput: {
            question: string;
            spaces: string[];
            content_type?: string;
            tags?: string[];
            min_weight?: number;
            moderation_filter?: components["schemas"]["ModerationFilter"];
            include_comments?: boolean;
            /** @default 10 */
            limit: number;
        };
        PublishResult: {
            composite_id: string;
            published_to: string[];
            space_ids: string[];
            group_ids: string[];
            results: components["schemas"]["LocationResult"][];
        };
        RetractResult: {
            retracted_from: string[];
            results: components["schemas"]["LocationResult"][];
        };
        ReviseResult: {
            /** Format: date-time */
            revised_at: string;
            memory_id: string;
        };
        LocationResult: {
            location: string;
            /** @enum {string} */
            status: "success" | "failed" | "skipped";
            error?: string;
        };
        ModerateResult: {
            memory_id: string;
            action: components["schemas"]["ModerationAction"];
            moderation_status: string;
            moderated_by: string;
            /** Format: date-time */
            moderated_at: string;
            location: string;
        };
        SearchSpaceResult: {
            spaces_searched: string[] | "all_public";
            groups_searched: string[];
            memories: {
                [key: string]: unknown;
            }[];
            total: number;
            offset: number;
            limit: number;
            hasMore: boolean;
        };
        QuerySpaceResult: {
            question: string;
            spaces_queried: string[];
            memories: {
                [key: string]: unknown;
            }[];
            total: number;
        };
        GhostConfig: {
            enabled: boolean;
            public_ghost_enabled: boolean;
            default_friend_trust: number;
            default_public_trust: number;
            per_user_trust: {
                [key: string]: number;
            };
            blocked_users: string[];
            /** @enum {string} */
            enforcement_mode: "query" | "prompt" | "hybrid";
        };
        UpdateGhostConfigInput: {
            enabled?: boolean;
            public_ghost_enabled?: boolean;
            default_friend_trust?: number;
            default_public_trust?: number;
            /** @enum {string} */
            enforcement_mode?: "query" | "prompt" | "hybrid";
        };
        GhostConfigResult: {
            success: boolean;
            config?: components["schemas"]["GhostConfig"];
            message: string;
        };
        TrustResult: {
            success: boolean;
            message: string;
        };
        CheckAccessResult: {
            accessible: boolean;
            /** @enum {string} */
            trust_tier: "full_access" | "partial_access" | "summary_only" | "metadata_only" | "existence_only";
            reason?: string;
        };
        SearchAsGhostInput: {
            /** @description The user whose memories to search as ghost */
            owner_user_id: string;
            query: string;
            /** @default 10 */
            limit: number;
            /** @default 0 */
            offset: number;
        };
        SearchAsGhostResult: {
            memories: components["schemas"]["RedactedMemory"][];
            total: number;
            offset: number;
            limit: number;
            hasMore: boolean;
            /**
             * @description The resolved trust tier for the caller accessing the target user
             * @enum {string}
             */
            trust_tier: "full_access" | "partial_access" | "summary_only" | "metadata_only" | "existence_only";
        };
        RedactedMemory: {
            memory_id: string;
            /** @enum {string} */
            trust_tier: "full_access" | "partial_access" | "summary_only" | "metadata_only" | "existence_only";
            /** @description Content redacted based on trust tier */
            content: string;
            tags: string[];
            access_level: string;
        };
        UserPreferences: {
            user_id: string;
            templates: components["schemas"]["TemplatePreferences"];
            search: components["schemas"]["SearchPreferences"];
            location: components["schemas"]["LocationPreferences"];
            privacy: components["schemas"]["PrivacyPreferences"];
            notifications: components["schemas"]["NotificationPreferences"];
            display: components["schemas"]["DisplayPreferences"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TemplatePreferences: {
            auto_suggest?: boolean;
            suggestion_threshold?: number;
            max_suggestions?: number;
            show_preview?: boolean;
            remember_choice?: boolean;
            suppressed_categories?: string[];
            suppressed_templates?: string[];
            always_suggest?: string[];
        };
        SearchPreferences: {
            default_limit?: number;
            include_low_trust?: boolean;
            weight_by_access?: boolean;
            weight_by_recency?: boolean;
            default_alpha?: number;
        };
        LocationPreferences: {
            auto_capture?: boolean;
            /** @enum {string} */
            precision?: "exact" | "approximate" | "city" | "none";
            share_with_memories?: boolean;
        };
        PrivacyPreferences: {
            default_trust_level?: number;
            allow_cross_user_access?: boolean;
            auto_approve_requests?: boolean;
            audit_logging?: boolean;
        };
        NotificationPreferences: {
            trust_violations?: boolean;
            access_requests?: boolean;
            memory_reminders?: boolean;
            relationship_suggestions?: boolean;
        };
        DisplayPreferences: {
            date_format?: string;
            time_format?: string;
            timezone?: string;
            language?: string;
        };
        /** @description Partial update — only include fields to change */
        UpdatePreferencesInput: {
            templates?: components["schemas"]["TemplatePreferences"];
            search?: components["schemas"]["SearchPreferences"];
            location?: components["schemas"]["LocationPreferences"];
            privacy?: components["schemas"]["PrivacyPreferences"];
            notifications?: components["schemas"]["NotificationPreferences"];
            display?: components["schemas"]["DisplayPreferences"];
        };
    };
    responses: {
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "kind": "validation",
                 *         "message": "Content is required",
                 *         "context": {
                 *           "fields": {
                 *             "content": [
                 *               "must not be empty"
                 *             ]
                 *           }
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "kind": "unauthorized",
                 *         "message": "Invalid or missing authentication token",
                 *         "context": {}
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Insufficient permissions */
        ForbiddenError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "kind": "forbidden",
                 *         "message": "Insufficient permissions for this operation",
                 *         "context": {}
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "kind": "not_found",
                 *         "message": "Memory not found",
                 *         "context": {
                 *           "resource": "memory",
                 *           "id": "abc-123"
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Memory UUID */
        memoryId: string;
        /** @description Relationship UUID */
        relationshipId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    appGetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    appGetVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service version info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version: string;
                        environment: string;
                        /** @enum {string} */
                        tier: "app";
                    };
                };
            };
        };
    };
    appCreateAndPublishProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProfileInput"];
            };
        };
        responses: {
            /** @description Profile created and published */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateProfileResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            /** @description Profile already exists (singleton per user) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    appRetractProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory UUID */
                memoryId: components["parameters"]["memoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile retracted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        retracted: true;
                    };
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    appUpdateAndRepublishProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory UUID */
                memoryId: components["parameters"]["memoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileInput"];
            };
        };
        responses: {
            /** @description Profile updated and republished */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateProfileResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    appSearchProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchProfilesInput"];
            };
        };
        responses: {
            /** @description Profile search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchProfilesResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appCreateMemory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemoryInput"];
            };
        };
        responses: {
            /** @description Memory created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateMemoryResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appDeleteMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory UUID */
                memoryId: components["parameters"]["memoryId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeleteMemoryInput"];
            };
        };
        responses: {
            /** @description Memory deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteMemoryResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    appUpdateMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory UUID */
                memoryId: components["parameters"]["memoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemoryInput"];
            };
        };
        responses: {
            /** @description Memory updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateMemoryResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    appSearchMemories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchMemoryInput"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchMemoryResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appFindSimilarMemories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindSimilarInput"];
            };
        };
        responses: {
            /** @description Similar memories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindSimilarResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appQueryMemories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryMemoryInput"];
            };
        };
        responses: {
            /** @description Query results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryMemoryResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appCreateRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRelationshipInput"];
            };
        };
        responses: {
            /** @description Relationship created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRelationshipResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appDeleteRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relationship UUID */
                relationshipId: components["parameters"]["relationshipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relationship deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteRelationshipResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    appUpdateRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relationship UUID */
                relationshipId: components["parameters"]["relationshipId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRelationshipInput"];
            };
        };
        responses: {
            /** @description Relationship updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRelationshipResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    appSearchRelationships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRelationshipInput"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchRelationshipResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appPublishToSpace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishInput"];
            };
        };
        responses: {
            /** @description Memory published */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appRetractFromSpace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetractInput"];
            };
        };
        responses: {
            /** @description Memory retracted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetractResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appReviseInSpace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviseInput"];
            };
        };
        responses: {
            /** @description Content revised */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviseResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appModerateSpace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerateInput"];
            };
        };
        responses: {
            /** @description Moderation action applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerateResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
        };
    };
    appSearchSpaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchSpaceInput"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSpaceResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appQuerySpaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuerySpaceInput"];
            };
        };
        responses: {
            /** @description Query results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuerySpaceResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appGetGhostConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ghost configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GhostConfigResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appUpdateGhostConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGhostConfigInput"];
            };
        };
        responses: {
            /** @description Updated ghost config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GhostConfigResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appSetUserTrust: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_user_id: string;
                    trust_level: number;
                };
            };
        };
        responses: {
            /** @description Trust level set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appRemoveUserTrust: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_user_id: string;
                };
            };
        };
        responses: {
            /** @description Trust level removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appBlockUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_user_id: string;
                };
            };
        };
        responses: {
            /** @description User blocked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appUnblockUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_user_id: string;
                };
            };
        };
        responses: {
            /** @description User unblocked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appCheckAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    memory_id: string;
                    accessor_user_id: string;
                };
            };
        };
        responses: {
            /** @description Access check result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckAccessResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appSearchAsGhost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchAsGhostInput"];
            };
        };
        responses: {
            /** @description Trust-filtered search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchAsGhostResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            /** @description Ghost access not enabled for target user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    appGetPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    appUpdatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePreferencesInput"];
            };
        };
        responses: {
            /** @description Updated preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
}
