/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service version */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a memory */
        post: operations["createMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/memories/{memoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft delete a memory */
        delete: operations["deleteMemory"];
        options?: never;
        head?: never;
        /** Update a memory */
        patch: operations["updateMemory"];
        trace?: never;
    };
    "/api/svc/v1/memories/{memoryId}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's rating for a memory */
        get: operations["getMyRating"];
        /** Submit or update a rating for a memory */
        put: operations["rateMemory"];
        post?: never;
        /** Retract a previously submitted rating */
        delete: operations["retractRating"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/memories/by-rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch memories sorted by Bayesian average rating */
        post: operations["memoriesByRating"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/memories/by-discovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Browse or search memories with discovery interleaving (rated + unrated at 4:1 ratio) */
        post: operations["memoriesByDiscovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/memories/by-recommendation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Personalized memory feed sorted by similarity to user preference centroid */
        post: operations["memoriesByRecommendation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/memories/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hybrid search (BM25 + semantic) */
        post: operations["searchMemories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/memories/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find similar memories by vector similarity */
        post: operations["findSimilarMemories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/memories/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Semantic query (vector-only) */
        post: operations["queryMemories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/memories/by-time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch memories sorted by creation time */
        post: operations["memoriesByTime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/memories/by-density": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch memories sorted by relationship count */
        post: operations["memoriesByDensity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/memories/by-time-slice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search memories with chronological ordering via parallel time-bucketed searches
         * @description Combines text search with chronological ordering. Partitions the time axis
         *     into 14 buckets, runs parallel searches per bucket, and concatenates results
         *     in chronological order. Desc uses exponentially-graded buckets anchored at now;
         *     asc uses equal-width buckets spanning from oldest memory to now.
         */
        post: operations["memoriesByTimeSlice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/memories/by-density-slice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search memories with density ordering via parallel density-bucketed searches
         * @description Combines text search with relationship-density ordering. Partitions the
         *     relationship_count axis into 9 buckets, runs parallel searches per bucket,
         *     and concatenates results in density order. Desc uses graded buckets
         *     (most-connected first); asc uses equal-width buckets spanning from 0 to
         *     the max relationship_count in the collection.
         */
        post: operations["memoriesByDensitySlice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/memories/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk import text as chunked memories
         * @description Accepts one or more text items, splits each into ~3K token chunks,
         *     creates memories via MemoryService, generates a parent summary via
         *     HaikuClient, and links chunks to parent via part_of relationships.
         */
        post: operations["memoriesImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job status
         * @description Returns the current state of a job including progress and step details.
         */
        get: operations["getJobStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a running job
         * @description Requests cancellation of a running job. The worker checks this flag between steps.
         */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a relationship between memories */
        post: operations["createRelationship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/relationships/{relationshipId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a relationship */
        delete: operations["deleteRelationship"];
        options?: never;
        head?: never;
        /** Update a relationship */
        patch: operations["updateRelationship"];
        trace?: never;
    };
    "/api/svc/v1/relationships/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search relationships */
        post: operations["searchRelationships"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/spaces/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a memory to shared spaces
         * @description Returns a confirmation token. Call /confirmations/{token}/confirm to execute.
         *     Content is checked by automated moderation before publishing. If content violates
         *     moderation policy (hate speech, extremism, violence incitement, CSAM, self-harm
         *     encouragement), a 400 ValidationError is returned with context.fields.moderation=['blocked']
         *     and context.fields.category indicating the violation type.
         */
        post: operations["publishToSpace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/spaces/retract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retract a memory from shared spaces
         * @description Returns a confirmation token. Call /confirmations/{token}/confirm to execute.
         */
        post: operations["retractFromSpace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/spaces/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose a content revision
         * @description Returns a confirmation token. Call /confirmations/{token}/confirm to execute.
         *     Content is checked by automated moderation before revising. If content violates
         *     moderation policy, a 400 ValidationError is returned with context.fields.moderation=['blocked'].
         */
        post: operations["reviseInSpace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/spaces/moderate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Moderate content in a space or group */
        post: operations["moderateSpace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/spaces/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search shared spaces */
        post: operations["searchSpaces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/spaces/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Semantic query across shared spaces */
        post: operations["querySpaces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/spaces/by-discovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Browse or search spaces with discovery interleaving (rated + unrated at 4:1 ratio) */
        post: operations["spacesByDiscovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/spaces/by-recommendation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Personalized space memory feed sorted by similarity to user preference centroid */
        post: operations["spacesByRecommendation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/confirmations/{token}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm a pending action */
        post: operations["confirmAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/confirmations/{token}/deny": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deny a pending action */
        post: operations["denyAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user preferences */
        get: operations["getPreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user preferences */
        patch: operations["updatePreferences"];
        trace?: never;
    };
    "/api/svc/v1/trust/ghost-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ghost configuration */
        get: operations["getGhostConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update ghost configuration */
        patch: operations["updateGhostConfig"];
        trace?: never;
    };
    "/api/svc/v1/trust/set-user-trust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set trust level for a specific user */
        post: operations["setUserTrust"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/trust/remove-user-trust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove custom trust level for a user (revert to default) */
        post: operations["removeUserTrust"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/trust/block-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block a user */
        post: operations["blockUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/trust/unblock-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unblock a user */
        post: operations["unblockUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/svc/v1/trust/check-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check memory access for a user */
        post: operations["checkAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /** @enum {string} */
                kind: "validation" | "not_found" | "unauthorized" | "forbidden" | "conflict" | "rate_limit" | "external" | "internal";
                message: string;
                context: {
                    [key: string]: unknown;
                };
            };
        };
        /** @enum {string} */
        ContentType: "code" | "note" | "documentation" | "reference" | "todo" | "checklist" | "project" | "goal" | "habit" | "email" | "conversation" | "meeting" | "person" | "article" | "webpage" | "social" | "image" | "video" | "audio" | "song" | "transcript" | "presentation" | "spreadsheet" | "pdf" | "screenplay" | "recipe" | "idea" | "quote" | "poetry" | "journal" | "memory" | "event" | "bookmark" | "form" | "location" | "invoice" | "contract" | "system" | "action" | "audit" | "history" | "ghost" | "comment" | "profile" | "agent";
        /**
         * @default exclude
         * @enum {string}
         */
        DeletedFilter: "exclude" | "include" | "only";
        SearchFilters: {
            types?: components["schemas"]["ContentType"][];
            /** @description Content types to exclude from results. Takes precedence if a type appears in both types and exclude_types. */
            exclude_types?: components["schemas"]["ContentType"][];
            tags?: string[];
            weight_min?: number;
            weight_max?: number;
            trust_min?: number;
            trust_max?: number;
            /** Format: date-time */
            date_from?: string;
            /** Format: date-time */
            date_to?: string;
            has_relationships?: boolean;
            /** @description Minimum rating_bayesian score (e.g. 4.0 for highly-rated memories) */
            rating_min?: number;
            /** @description Inclusive lower bound on relationship_count */
            relationship_count_min?: number;
            /** @description Inclusive upper bound on relationship_count */
            relationship_count_max?: number;
            /** @description Filter to memories in these relationships (resolved to memory_ids by caller) */
            relationship_ids?: string[];
            /** @description Pre-resolved set of memory IDs to filter by (e.g. from relationship_ids) */
            memory_ids?: string[];
        };
        GhostSearchContext: {
            accessor_trust_level: number;
            owner_user_id: string;
            include_ghost_content?: boolean;
        };
        /** @enum {string} */
        ModerationAction: "approve" | "reject" | "remove";
        /**
         * @default approved
         * @enum {string}
         */
        ModerationFilter: "approved" | "pending" | "rejected" | "removed" | "all";
        CreateMemoryInput: {
            content: string;
            title?: string;
            type?: components["schemas"]["ContentType"];
            weight?: number;
            trust?: number;
            tags?: string[];
            references?: string[];
            template_id?: string;
            parent_id?: string | null;
            thread_root_id?: string | null;
            moderation_flags?: string[];
            context_summary?: string;
            context_conversation_id?: string;
            /**
             * Format: date-time
             * @description ISO 8601 datetime for agent follow-up reminders
             */
            follow_up_at?: string;
        };
        SearchMemoryInput: {
            query: string;
            /**
             * @description Balance between semantic (1.0) and keyword (0.0) search
             * @default 0.7
             */
            alpha: number;
            /** @default 10 */
            limit: number;
            /** @default 0 */
            offset: number;
            filters?: components["schemas"]["SearchFilters"];
            /** @default true */
            include_relationships: boolean;
            deleted_filter?: components["schemas"]["DeletedFilter"];
            ghost_context?: components["schemas"]["GhostSearchContext"];
        };
        FindSimilarInput: {
            /** @description Find memories similar to this memory (provide memory_id or text) */
            memory_id?: string;
            /** @description Find memories similar to this text (provide memory_id or text) */
            text?: string;
            /** @default 10 */
            limit: number;
            /** @default 0.7 */
            min_similarity: number;
            include_relationships?: boolean;
            deleted_filter?: components["schemas"]["DeletedFilter"];
            ghost_context?: components["schemas"]["GhostSearchContext"];
        };
        QueryMemoryInput: {
            query: string;
            /** @default 5 */
            limit: number;
            /** @default 0.6 */
            min_relevance: number;
            filters?: components["schemas"]["SearchFilters"];
            deleted_filter?: components["schemas"]["DeletedFilter"];
            ghost_context?: components["schemas"]["GhostSearchContext"];
        };
        UpdateMemoryInput: {
            content?: string;
            title?: string;
            type?: string;
            weight?: number;
            trust?: number;
            tags?: string[];
            references?: string[];
            parent_id?: string | null;
            thread_root_id?: string | null;
            moderation_flags?: string[];
        };
        DeleteMemoryInput: {
            reason?: string;
        };
        CreateMemoryResult: {
            memory_id: string;
            /** Format: date-time */
            created_at: string;
        };
        SearchMemoryResult: {
            memories: {
                [key: string]: unknown;
            }[];
            relationships?: {
                [key: string]: unknown;
            }[];
            total: number;
            offset: number;
            limit: number;
        };
        FindSimilarResult: {
            similar_memories: ({
                id: string;
                similarity: number;
            } & {
                [key: string]: unknown;
            })[];
            total: number;
        };
        QueryMemoryResult: {
            memories: ({
                id: string;
                relevance: number;
            } & {
                [key: string]: unknown;
            })[];
            total: number;
        };
        TimeModeRequest: {
            /** @default 10 */
            limit: number;
            /** @default 0 */
            offset: number;
            /**
             * @default desc
             * @enum {string}
             */
            direction: "asc" | "desc";
            filters?: components["schemas"]["SearchFilters"];
            deleted_filter?: components["schemas"]["DeletedFilter"];
            ghost_context?: components["schemas"]["GhostSearchContext"];
        };
        TimeModeResult: {
            memories: {
                [key: string]: unknown;
            }[];
            total: number;
            offset: number;
            limit: number;
        };
        DensityModeRequest: {
            /** @default 10 */
            limit: number;
            /** @default 0 */
            offset: number;
            /** @default 0 */
            min_relationship_count: number;
            filters?: components["schemas"]["SearchFilters"];
            deleted_filter?: components["schemas"]["DeletedFilter"];
            ghost_context?: components["schemas"]["GhostSearchContext"];
        };
        DensityModeResult: {
            memories: {
                [key: string]: unknown;
            }[];
            total: number;
            offset: number;
            limit: number;
        };
        RateMemoryRequest: {
            rating: number;
        };
        RatingResponse: {
            previousRating: number | null;
            newRating: number;
            ratingCount: number;
            ratingAvg: number | null;
        };
        UserRatingResponse: {
            rating: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RatingModeRequest: {
            /**
             * @default desc
             * @enum {string}
             */
            direction: "desc" | "asc";
            /** @default 10 */
            limit: number;
            /** @default 0 */
            offset: number;
            filters?: components["schemas"]["SearchFilters"];
            deleted_filter?: components["schemas"]["DeletedFilter"];
            ghost_context?: components["schemas"]["GhostSearchContext"];
        };
        RatingModeResult: {
            memories: {
                [key: string]: unknown;
            }[];
            total: number;
            offset: number;
            limit: number;
        };
        DiscoveryModeRequest: {
            /** @description Optional search query. When provided, pools are ranked by relevance (hybrid search) instead of rating/recency. */
            query?: string;
            /** @default 10 */
            limit: number;
            /** @default 0 */
            offset: number;
            filters?: components["schemas"]["SearchFilters"];
            deleted_filter?: components["schemas"]["DeletedFilter"];
            ghost_context?: components["schemas"]["GhostSearchContext"];
        };
        DiscoveryModeResult: {
            memories: ({
                /** @description Whether this item was surfaced as a discovery slot */
                is_discovery?: boolean;
            } & {
                [key: string]: unknown;
            })[];
            total: number;
            offset: number;
            limit: number;
        };
        DiscoverySpaceInput: {
            /** @description Optional search query. When provided, pools are ranked by relevance (hybrid search) instead of rating/recency. */
            query?: string;
            spaces?: string[];
            groups?: string[];
            content_type?: string;
            tags?: string[];
            min_weight?: number;
            max_weight?: number;
            /** Format: date-time */
            date_from?: string;
            /** Format: date-time */
            date_to?: string;
            moderation_filter?: components["schemas"]["ModerationFilter"];
            include_comments?: boolean;
            /** @default 10 */
            limit: number;
            /** @default 0 */
            offset: number;
        };
        DiscoverySpaceResult: {
            spaces_searched: string[] | "all_public";
            groups_searched: string[];
            memories: ({
                is_discovery?: boolean;
            } & {
                [key: string]: unknown;
            })[];
            total: number;
            offset: number;
            limit: number;
        };
        RecommendationModeRequest: {
            /** @description User ID for preference centroid computation */
            userId: string;
            /** @description Optional search query to narrow candidates */
            query?: string;
            /** @default 20 */
            limit: number;
            /** @default 0 */
            offset: number;
            filters?: components["schemas"]["SearchFilters"];
            deleted_filter?: components["schemas"]["DeletedFilter"];
            ghost_context?: components["schemas"]["GhostSearchContext"];
        };
        RecommendationModeResult: {
            memories: ({
                /** @description Similarity to user preference centroid (0-100) */
                similarity_pct?: number;
            } & {
                [key: string]: unknown;
            })[];
            /** @description Number of highly-rated memories in the centroid */
            profileSize: number;
            /** @description True when user has fewer than 5 highly-rated memories */
            insufficientData: boolean;
            /**
             * @description Set when falling back to byDiscovery due to insufficient data
             * @enum {string}
             */
            fallback_sort_mode?: "byDiscovery";
            total: number;
            offset: number;
            limit: number;
        };
        RecommendationSpaceInput: {
            /** @description User ID for preference centroid computation */
            userId: string;
            /** @description Optional search query to narrow candidates */
            query?: string;
            spaces?: string[];
            groups?: string[];
            content_type?: string;
            tags?: string[];
            min_weight?: number;
            max_weight?: number;
            /** Format: date-time */
            date_from?: string;
            /** Format: date-time */
            date_to?: string;
            moderation_filter?: components["schemas"]["ModerationFilter"];
            include_comments?: boolean;
            /** @default 20 */
            limit: number;
            /** @default 0 */
            offset: number;
        };
        RecommendationSpaceResult: {
            spaces_searched: string[] | "all_public";
            groups_searched: string[];
            memories: ({
                /** @description Similarity to user preference centroid (0-100) */
                similarity_pct?: number;
            } & {
                [key: string]: unknown;
            })[];
            /** @description Number of highly-rated memories in the centroid */
            profileSize: number;
            /** @description True when user has fewer than 5 highly-rated memories */
            insufficientData: boolean;
            /**
             * @description Set when falling back to byDiscovery due to insufficient data
             * @enum {string}
             */
            fallback_sort_mode?: "byDiscovery";
            total: number;
            offset: number;
            limit: number;
        };
        TimeSliceSearchInput: {
            query: string;
            /** @default 10 */
            limit: number;
            /** @default 0 */
            offset: number;
            /** @enum {string} */
            direction: "asc" | "desc";
            filters?: components["schemas"]["SearchFilters"];
        };
        TimeSliceSearchResult: {
            memories: {
                [key: string]: unknown;
            }[];
            total: number;
        };
        DensitySliceSearchInput: {
            query: string;
            /** @default 10 */
            limit: number;
            /** @default 0 */
            offset: number;
            /** @enum {string} */
            direction: "asc" | "desc";
            filters?: components["schemas"]["SearchFilters"];
        };
        DensitySliceSearchResult: {
            memories: {
                [key: string]: unknown;
            }[];
            total: number;
        };
        UpdateMemoryResult: {
            memory_id: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
            updated_fields: string[];
        };
        DeleteMemoryResult: {
            memory_id: string;
            /** Format: date-time */
            deleted_at: string;
            orphaned_relationship_ids: string[];
        };
        ImportItem: {
            /** @description Raw text content (mutually exclusive with file_url) */
            content?: string;
            /** @description Signed HTTPS URL for file download (mutually exclusive with content) */
            file_url?: string;
            /** @description MIME type of the file (required when file_url is provided) */
            mime_type?: string;
            /** @description Original filename for metadata */
            source_filename?: string;
        };
        ImportInput: {
            /** @description One or more items to import */
            items: components["schemas"]["ImportItem"][];
            /**
             * @description Max tokens per chunk
             * @default 3000
             */
            chunk_size: number;
            /** @description Conversation that triggered the import */
            context_conversation_id?: string;
        };
        ImportItemResult: {
            /** @description UUID for this import item */
            import_id: string;
            /** @description Summary memory ID */
            parent_memory_id: string;
            /** @description Ordered chunk memory IDs */
            chunk_memory_ids: string[];
            /** @description Number of chunks created */
            chunk_count: number;
            /** @description Original filename if provided */
            source_filename?: string;
            /** @description Generated summary text */
            summary: string;
        };
        ImportResult: {
            /** @description Results per item */
            items: components["schemas"]["ImportItemResult"][];
            /** @description Total memories created (parents + chunks) */
            total_memories_created: number;
        };
        CreateRelationshipInput: {
            memory_ids: string[];
            relationship_type: string;
            observation: string;
            /** @default 0.5 */
            strength: number;
            /** @default 0.8 */
            confidence: number;
            tags?: string[];
            context_summary?: string;
            context_conversation_id?: string;
        };
        SearchRelationshipInput: {
            query: string;
            relationship_types?: string[];
            strength_min?: number;
            confidence_min?: number;
            tags?: string[];
            /** @default 10 */
            limit: number;
            /** @default 0 */
            offset: number;
            deleted_filter?: components["schemas"]["DeletedFilter"];
        };
        UpdateRelationshipInput: {
            relationship_type?: string;
            observation?: string;
            strength?: number;
            confidence?: number;
            tags?: string[];
        };
        CreateRelationshipResult: {
            relationship_id: string;
            memory_ids: string[];
            /** Format: date-time */
            created_at: string;
        };
        SearchRelationshipResult: {
            relationships: {
                [key: string]: unknown;
            }[];
            total: number;
            offset: number;
            limit: number;
        };
        UpdateRelationshipResult: {
            relationship_id: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
            updated_fields: string[];
        };
        DeleteRelationshipResult: {
            relationship_id: string;
            memories_updated: number;
        };
        PublishInput: {
            memory_id: string;
            spaces?: string[];
            groups?: string[];
            additional_tags?: string[];
        };
        RetractInput: {
            memory_id: string;
            spaces?: string[];
            groups?: string[];
        };
        ReviseInput: {
            memory_id: string;
        };
        ModerateInput: {
            memory_id: string;
            space_id?: string;
            group_id?: string;
            action: components["schemas"]["ModerationAction"];
            reason?: string;
        };
        SearchSpaceInput: {
            query: string;
            spaces?: string[];
            groups?: string[];
            /**
             * @default hybrid
             * @enum {string}
             */
            search_type: "hybrid" | "bm25" | "semantic";
            content_type?: string;
            tags?: string[];
            min_weight?: number;
            max_weight?: number;
            /** Format: date-time */
            date_from?: string;
            /** Format: date-time */
            date_to?: string;
            moderation_filter?: components["schemas"]["ModerationFilter"];
            include_comments?: boolean;
            /** @default 10 */
            limit: number;
            /** @default 0 */
            offset: number;
            /**
             * @description Enable content-hash deduplication across collections (default true)
             * @default true
             */
            dedupe: boolean;
        };
        QuerySpaceInput: {
            question: string;
            spaces: string[];
            content_type?: string;
            tags?: string[];
            min_weight?: number;
            /** Format: date-time */
            date_from?: string;
            /** Format: date-time */
            date_to?: string;
            moderation_filter?: components["schemas"]["ModerationFilter"];
            include_comments?: boolean;
            /** @default 10 */
            limit: number;
        };
        TokenResult: {
            token: string;
        };
        ConfirmResult: {
            action: string;
            success: boolean;
            composite_id?: string;
            published_to?: string[];
            retracted_from?: string[];
            /** Format: date-time */
            revised_at?: string;
            space_ids?: string[];
            group_ids?: string[];
            failed?: string[];
            results?: {
                location: string;
                /** @enum {string} */
                status: "success" | "failed" | "skipped";
                error?: string;
            }[];
            memory_id?: string;
        };
        DenyResult: {
            success: boolean;
        };
        ModerateResult: {
            memory_id: string;
            action: components["schemas"]["ModerationAction"];
            moderation_status: string;
            moderated_by: string;
            /** Format: date-time */
            moderated_at: string;
            location: string;
        };
        SearchSpaceResult: {
            spaces_searched: string[] | "all_public";
            groups_searched: string[];
            memories: ({
                /** @description Other collections where this memory also exists (populated when dedupe is enabled) */
                also_in?: {
                    /** @description Collection name where the duplicate exists */
                    source: string;
                    /** @description UUID of the duplicate memory */
                    id: string;
                }[];
            } & {
                [key: string]: unknown;
            })[];
            total: number;
            offset: number;
            limit: number;
        };
        QuerySpaceResult: {
            question: string;
            spaces_queried: string[];
            memories: {
                [key: string]: unknown;
            }[];
            total: number;
        };
        UserPreferences: {
            user_id: string;
            templates: components["schemas"]["TemplatePreferences"];
            search: components["schemas"]["SearchPreferences"];
            location: components["schemas"]["LocationPreferences"];
            privacy: components["schemas"]["PrivacyPreferences"];
            notifications: components["schemas"]["NotificationPreferences"];
            display: components["schemas"]["DisplayPreferences"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TemplatePreferences: {
            auto_suggest?: boolean;
            suggestion_threshold?: number;
            max_suggestions?: number;
            show_preview?: boolean;
            remember_choice?: boolean;
            suppressed_categories?: string[];
            suppressed_templates?: string[];
            always_suggest?: string[];
        };
        SearchPreferences: {
            default_limit?: number;
            include_low_trust?: boolean;
            weight_by_access?: boolean;
            weight_by_recency?: boolean;
            default_alpha?: number;
        };
        LocationPreferences: {
            auto_capture?: boolean;
            /** @enum {string} */
            precision?: "exact" | "approximate" | "city" | "none";
            share_with_memories?: boolean;
        };
        PrivacyPreferences: {
            default_trust_level?: number;
            allow_cross_user_access?: boolean;
            auto_approve_requests?: boolean;
            audit_logging?: boolean;
        };
        NotificationPreferences: {
            trust_violations?: boolean;
            access_requests?: boolean;
            memory_reminders?: boolean;
            relationship_suggestions?: boolean;
        };
        DisplayPreferences: {
            date_format?: string;
            time_format?: string;
            timezone?: string;
            language?: string;
        };
        /** @description Partial update — only include fields to change */
        UpdatePreferencesInput: {
            templates?: components["schemas"]["TemplatePreferences"];
            search?: components["schemas"]["SearchPreferences"];
            location?: components["schemas"]["LocationPreferences"];
            privacy?: components["schemas"]["PrivacyPreferences"];
            notifications?: components["schemas"]["NotificationPreferences"];
            display?: components["schemas"]["DisplayPreferences"];
        };
        GhostConfig: {
            enabled: boolean;
            public_ghost_enabled: boolean;
            default_friend_trust: number;
            default_public_trust: number;
            per_user_trust: {
                [key: string]: number;
            };
            blocked_users: string[];
            /** @enum {string} */
            enforcement_mode: "query" | "prompt" | "hybrid";
        };
        /** @description Partial update — only include fields to change */
        UpdateGhostConfigInput: {
            enabled?: boolean;
            public_ghost_enabled?: boolean;
            default_friend_trust?: number;
            default_public_trust?: number;
            /** @enum {string} */
            enforcement_mode?: "query" | "prompt" | "hybrid";
        };
        GhostConfigResult: {
            success: boolean;
            config?: components["schemas"]["GhostConfig"];
            message: string;
        };
        TrustResult: {
            success: boolean;
            message: string;
        };
        /** @enum {string} */
        JobType: "import" | "rem_cycle";
        /** @enum {string} */
        JobStatus: "pending" | "running" | "completed" | "completed_with_errors" | "failed" | "cancelled" | "paused";
        /** @enum {string} */
        JobStepStatus: "pending" | "running" | "completed" | "failed" | "skipped";
        JobError: {
            code: string;
            message: string;
            step_id?: string;
        };
        JobStep: {
            id: string;
            label: string;
            status: components["schemas"]["JobStepStatus"];
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            error?: components["schemas"]["JobError"];
        };
        Job: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["JobType"];
            status: components["schemas"]["JobStatus"];
            progress: number;
            current_step?: string | null;
            steps: components["schemas"]["JobStep"][];
            user_id?: string | null;
            params?: {
                [key: string]: unknown;
            };
            result?: {
                [key: string]: unknown;
            } | null;
            error?: components["schemas"]["JobError"];
            ttl_hours: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
        };
        CancelJobResponse: {
            /** @enum {string} */
            status: "cancelled";
        };
    };
    responses: {
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "kind": "validation",
                 *         "message": "Content is required",
                 *         "context": {
                 *           "fields": {
                 *             "content": [
                 *               "must not be empty"
                 *             ]
                 *           }
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "kind": "unauthorized",
                 *         "message": "Invalid or missing authentication token",
                 *         "context": {}
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Insufficient permissions */
        ForbiddenError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "kind": "forbidden",
                 *         "message": "Insufficient permissions for this operation",
                 *         "context": {}
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "kind": "not_found",
                 *         "message": "Memory not found",
                 *         "context": {
                 *           "resource": "memory",
                 *           "id": "abc-123"
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Memory UUID */
        memoryId: string;
        /** @description Relationship UUID */
        relationshipId: string;
        /** @description Confirmation token string */
        confirmationToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service version info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version: string;
                        environment: string;
                    };
                };
            };
        };
    };
    createMemory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemoryInput"];
            };
        };
        responses: {
            /** @description Memory created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateMemoryResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    deleteMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory UUID */
                memoryId: components["parameters"]["memoryId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeleteMemoryInput"];
            };
        };
        responses: {
            /** @description Memory deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteMemoryResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    updateMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory UUID */
                memoryId: components["parameters"]["memoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemoryInput"];
            };
        };
        responses: {
            /** @description Memory updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateMemoryResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getMyRating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory UUID */
                memoryId: components["parameters"]["memoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User's rating */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRatingResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    rateMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory UUID */
                memoryId: components["parameters"]["memoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateMemoryRequest"];
            };
        };
        responses: {
            /** @description Rating submitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            /** @description Cannot rate own memory or ghost mode */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFoundError"];
        };
    };
    retractRating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory UUID */
                memoryId: components["parameters"]["memoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rating retracted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    memoriesByRating: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingModeRequest"];
            };
        };
        responses: {
            /** @description Rating-sorted memories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingModeResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    memoriesByDiscovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoveryModeRequest"];
            };
        };
        responses: {
            /** @description Discovery-interleaved memories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryModeResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    memoriesByRecommendation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationModeRequest"];
            };
        };
        responses: {
            /** @description Recommendation-ranked memories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationModeResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    searchMemories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchMemoryInput"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchMemoryResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    findSimilarMemories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindSimilarInput"];
            };
        };
        responses: {
            /** @description Similar memories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindSimilarResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    queryMemories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryMemoryInput"];
            };
        };
        responses: {
            /** @description Query results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryMemoryResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    memoriesByTime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeModeRequest"];
            };
        };
        responses: {
            /** @description Chronologically sorted memories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeModeResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    memoriesByDensity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DensityModeRequest"];
            };
        };
        responses: {
            /** @description Density-sorted memories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DensityModeResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    memoriesByTimeSlice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeSliceSearchInput"];
            };
        };
        responses: {
            /** @description Chronologically-ordered search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeSliceSearchResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    memoriesByDensitySlice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DensitySliceSearchInput"];
            };
        };
        responses: {
            /** @description Density-ordered search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DensitySliceSearchResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    memoriesImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportInput"];
            };
        };
        responses: {
            /** @description Import job accepted */
            202: {
                headers: {
                    /** @description URL to poll for job status */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        job_id: string;
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    getJobStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelJobResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRelationshipInput"];
            };
        };
        responses: {
            /** @description Relationship created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRelationshipResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    deleteRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relationship UUID */
                relationshipId: components["parameters"]["relationshipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relationship deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteRelationshipResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    updateRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relationship UUID */
                relationshipId: components["parameters"]["relationshipId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRelationshipInput"];
            };
        };
        responses: {
            /** @description Relationship updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRelationshipResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    searchRelationships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRelationshipInput"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchRelationshipResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    publishToSpace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishInput"];
            };
        };
        responses: {
            /** @description Confirmation token generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    retractFromSpace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetractInput"];
            };
        };
        responses: {
            /** @description Confirmation token generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    reviseInSpace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviseInput"];
            };
        };
        responses: {
            /** @description Confirmation token generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    moderateSpace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerateInput"];
            };
        };
        responses: {
            /** @description Moderation action applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerateResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
            403: components["responses"]["ForbiddenError"];
        };
    };
    searchSpaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchSpaceInput"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSpaceResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    querySpaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuerySpaceInput"];
            };
        };
        responses: {
            /** @description Query results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuerySpaceResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    spacesByDiscovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverySpaceInput"];
            };
        };
        responses: {
            /** @description Discovery-interleaved space memories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverySpaceResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    spacesByRecommendation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationSpaceInput"];
            };
        };
        responses: {
            /** @description Recommendation-ranked space memories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationSpaceResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    confirmAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Confirmation token string */
                token: components["parameters"]["confirmationToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Action confirmed and executed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    denyAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Confirmation token string */
                token: components["parameters"]["confirmationToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Action denied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DenyResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    updatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePreferencesInput"];
            };
        };
        responses: {
            /** @description Updated preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    getGhostConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ghost configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GhostConfigResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    updateGhostConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGhostConfigInput"];
            };
        };
        responses: {
            /** @description Updated ghost config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GhostConfigResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    setUserTrust: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_user_id: string;
                    trust_level: number;
                };
            };
        };
        responses: {
            /** @description Trust level set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    removeUserTrust: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_user_id: string;
                };
            };
        };
        responses: {
            /** @description Trust level removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    blockUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_user_id: string;
                };
            };
        };
        responses: {
            /** @description User blocked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    unblockUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    target_user_id: string;
                };
            };
        };
        responses: {
            /** @description User unblocked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustResult"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    checkAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    memory_id: string;
                    accessor_user_id: string;
                };
            };
        };
        responses: {
            /** @description Access check result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessible: boolean;
                        /** @enum {string} */
                        trust_tier: "full_access" | "partial_access" | "summary_only" | "metadata_only" | "existence_only";
                        reason?: string;
                    };
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
}
